### ISSUE TITLE
Specify images are normalized

### ISSUE THREAD

**Issue by sahiljuneja** [Brok-Bucholtz/Project-Face-Generation#4]
In the helper.py when obtaining batches, you are already normalizing the images before yielding them.

I think, perhaps, this should be clarified in the notebook. That you are already normalizing the images, and it's not required to do so again.

This is currently based on the GAN MNIST notebook where it was being done in the notebook itself.

**Comment by Brok-Bucholtz** [comment]
Added details about the input data in commit https://github.com/Brok-Bucholtz/P5-Beta/commit/f7e3d7917cda0629f8179d3ea1a09b33424a592d.

**Comment by sahiljuneja** [comment]
Just to confirm one small detail, @Brok-Bucholtz 

You normalize the images between `-0.5` and `0.5` in `helper.py`.

The network output and the random uniform input (z) are between -1 and 1. 

So there will be a need to multiply the batch_images with 2, correct?
